const certificatesData = {
  Hackathons: [
    {
      title: "Won First Prize in AllenTech Hackathon",
      image: "res/images/certficates/Hackthons/allentech-hackthon.jpg",
      description: "Won First Prize in National Level Hackathon (Team Leader)",
      issuer: "Allenhouse",
      issuerUrl: "https://allenhouse.ac.in/",
    },
    {
      title: "Participated in Battle with Bytes",
      image: "res/images/certficates/Hackthons/battle-with-bytes.jpg",
      description: "National Level Hackathon (Team Leader)",
      issuer: "Allenhouse",
      issuerUrl: "https://allenhouse.ac.in/",
    },
    {
      title: "Participated in CodeFuse",
      image: "res/images/certficates/Hackthons/codefuse.jpg",
      description: "National Level Coding Competition (Team Leader)",
      issuer: "Allenhouse",
      issuerUrl: "https://allenhouse.ac.in/",
    },
    {
      title: "Participated in ISKCON Hackathon",
      image: "res/images/certficates/Hackthons/iskon-hackathon.jpg",
      description: "National Level Hackathon (Team Leader)",
      issuer: "ISKCON",
      issuerUrl: "https://iskconkanpur.com/",
    },
    {
      title: "Tech Expo",
      image: "res/images/certficates/Hackthons/Tech-expo.jpg",
      description: "Tech Project Presentation",
      issuer: "Allenhouse",
      issuerUrl: "https://allenhouse.ac.in/",
    },
    {
      title: "Tech Present",
      image: "res/images/certficates/Hackthons/tech-present.jpg",
      description: "Project Presentation",
      issuer: "Allenhouse",
      issuerUrl: "https://allenhouse.ac.in/",
    },
    {
      title: "Web Rachita",
      image: "res/images/certficates/Hackthons/web-rachita.jpg",
      description: "National Level Web Development Competition",
      issuer: "Allenhouse",
      issuerUrl: "https://allenhouse.ac.in/",
    },
  ],
  Internship: [
    {
      title: "Web Development Intern",
      image: "res/images/certficates/internship/IS-Web-dev-internship.jpg",
      description: "Completed 2 months Web Development Internship",
      issuer: "InternShip Studio",
      issuerUrl: "https://internshipstudio.com/",
    },
  ],
  Trainings: [
    {
      title: "HackerRank Python Basic",
      image: "res/images/certficates/Trainings/hackerrank python basic.png",
      description: "Python Basic Skill Certificate",
      issuer: "HackerRank",
      issuerUrl: "https://www.hackerrank.com/",
    },
    {
      title: "IBM Cloud Essentials",
      image: "res/images/certficates/Trainings/IBM-Cloud.jpg",
      description: "Cloud Computing Essentials",
      issuer: "IBM",
      issuerUrl: "https://www.ibm.com/",
    },
    {
      title: "IBM Data Science",
      image: "res/images/certficates/Trainings/IBM-data-science.jpg",
      description: "Data Science with Python",
      issuer: "IBM",
      issuerUrl: "https://www.ibm.com/",
    },
    {
      title: "Full Stack Development Training",
      image: "res/images/certficates/Trainings/IS-full-stack-training.jpg",
      description: "2 Months Full Stack Development Training",
      issuer: "InternShip Studio",
      issuerUrl: "https://internshipstudio.com/",
    },
    {
      title: "Full Stack Development",
      image: "res/images/certficates/Trainings/lits-full-stack.jpg",
      description: "Full Stack Web Development Training",
      issuer: "LITS",
      issuerUrl: "https://lakshyaitsolutions.com/",
    },
    {
      title: "Python NPTEL",
      image: "res/images/certficates/Trainings/NPTEL-python.jpg",
      description: "Python for Data Science",
      issuer: "NPTEL",
      issuerUrl: "https://nptel.ac.in/",
    },
  ],
  "Co-Curricular": [
    {
      title: "Brain Teaser Winner",
      image: "res/images/certficates/Co-curricular/Brainteaser.jpg",
      description: "Won Brain Teaser Competition",
      issuer: "Allenhouse",
      issuerUrl: "https://allenhouse.ac.in/",
    },
    {
      title: "Digital Productivity",
      image: "res/images/certficates/Co-curricular/Digital_productivity.jpg",
      description: "Digital Productivity Workshop",
      issuer: "NIIT Foundation",
      issuerUrl: "https://india.myp2e.org/",
    },
  ],
  "Extra-curricular": [
    {
      title: "Allen Talk",
      image: "res/images/certficates/Extra-curricular/AllenTalk.jpg",
      description: "Allen Talk Show Participant",
      issuer: "Allenhouse",
      issuerUrl: "https://allenhouse.ac.in/",
    },
    {
      title: "Energy Literacy Program",
      image: "res/images/certficates/Extra-curricular/Energy-Literacy.jpg",
      description: "Energy Literacy Workshop",
      issuer: "Energy Swaraj Foundation",
      issuerUrl: "https://energyswaraj.org/",
    },
    {
      title: "Volunteer at Exuberance'23",
      image:
        "res/images/certficates/Extra-curricular/voluteer-exuberance-23.jpg",
      description: "Technical Event Volunteer",
      issuer: "Allenhouse",
      issuerUrl: "https://allenhouse.ac.in/",
    },
    {
      title: "Yoga Day",
      image: "res/images/certficates/Extra-curricular/yoga-pledge.jpg",
      description: "International Yoga Day Participation",
      issuer: "CSJM University",
      issuerUrl: "https://csjmu.ac.in/",
    },
  ],
};
