const testimonialsData = [
  // {
  //   name: "Sachin Sharma",
  //   role: "Client — Student Sahayak App",
  //   icon: "fas fa-user-graduate",
  //   color: "#08e8de",
  //   stars: 5,
  //   text: "Ramanand delivered the entire Student Sahayak app — from design to Play Store deployment — with clean code and clear communication throughout. Genuinely impressed by the quality and speed.",
  // },
  {
    name: "Pankaj Kumar Asnani",
    role: "Founder — Pro Route",
    icon: "fas fa-shield-alt",
    color: "#0284c7",
    stars: 5,
    text: "The Pro Route website is exactly what we needed. It's sleek, professional, and perfectly showcases our AI dashcam technology. Highly recommend for any business looking for a premium web presence.",
  },
  {
    name: "Abhinav Yadav",
    role: "App Owner — Fitlix",
    icon: "fas fa-dumbbell",
    color: "#f59e0b",
    stars: 5,
    text: "Working with Ramanand on the Fitlix app was a breeze. He's a skilled Flutter developer who understands both design and performance. The app is fast, looks great, and our users love it.",
  },
  {
    name: "श्री आयुषाचार्य गुरुजी",
    role: "Director — Spiritual Services",
    icon: "fas fa-om",
    color: "#d97706",
    stars: 5,
    text: "Ramanand built a beautiful and culturally aligned website for our spiritual services (Kalsharp Dosh Trimbakeshwar). He was patient with our requirements and delivered a product that truly represents our brand.",
  },
  {
    name: "Vikram Singh",
    role: "CEO — S.K. Construction",
    icon: "fas fa-building",
    color: "#64748b",
    stars: 5,
    text: "Delivered a high-performance corporate website in just 10 days! Ramanand's speed and quality are unmatched. The site has greatly improved our online visibility and professional image.",
  },
  {
    name: "Sarvendra",
    role: "Founder — USH Academy",
    icon: "fas fa-graduation-cap",
    color: "#8b5cf6",
    stars: 5,
    text: "The SaaS e-learning platform Ramanand built for us is top-notch. It handles course sales, student management, and payments flawlessly. A complete solution delivered ahead of schedule.",
  },
];
